apiVersion: apps/v1
kind: Deployment
metadata:
	name: deepmediabotdiscord
spec:
	selector:
		matchLabels:
			app: DeepDiscordbot
		replicas: 1
		template:
			metadata:
				labels:
					app: DeepDiscordbot
				spec:
					containers:
					- name: DeepDiscordbot
					  image: kwazinator/deepmediabot:firstpush